[workspace]
resolver = "3"

default-members = [
    "project-mapper-core",
    "project-mapper-runtime",
    "project-mapper-macro",
    "project-mapper-base",
]

members = [ "project-mapper-base","project-mapper-core", "project-mapper-runtime", "project-mapper-macro"]

[workspace.package]
version = "0.1.0"
categories = ["multimedia"]
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
# Core workspace dependencies
project-mapper-runtime = { path = "project-mapper-runtime" }
project-mapper-core = { path = "project-mapper-core", features = ["change-tracking"]}
project-mapper-macro = { path = "project-mapper-macro"}
project-mapper-base = { path = "project-mapper-base"}

# Shared dependencies for all projects
anyhow = "1.0.98"
serde = { version = "1", features = ["derive"] }
typetag = "0.1"