[package]
name = "project-mapper-base"
version.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
project-mapper-core.workspace = true
project-mapper-runtime.workspace = true
project-mapper-macro.workspace = true
anyhow.workspace = true
serde.workspace = true
typetag.workspace = true
inventory = "0.3.21"
simple_logger = "5.1.0"
log = "0.4.29"
winit = "0.30"
raw-window-handle = "0.6.2"
serde_json = "1.0.145"
schemars = "1.1.0"