[package]
name = "project-mapper-runtime"
version.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
winit = "0.29"
gst = { package = "gstreamer", version="0.23"  }
gst_video = { package = "gstreamer-video", version="0.23"  }
raw-window-handle = "0.6.2"

# Inherit dependencies from workspace
project-mapper-core = { workspace = true}
anyhow = {workspace = true}

