[package]
name = "project-mapper-runtime"
version.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
winit = "0.30"
gst = { package = "gstreamer", version="0.23"  }
gst_video = { package = "gstreamer-video", version="0.23"  }
raw-window-handle = "0.6.2"
log.workspace=true
ctrlc = "3"

# Inherit dependencies from workspace
project-mapper-core = { workspace = true}
anyhow = {workspace = true}

# Optional receiver dependencies
tokio = { version = "1.38", features = ["rt", "macros"], optional = true}
tokio-util = {version = "0.7", optional = true}
tower = {version = "0.4", features=["util"], optional=true}
# Optional HTTP receiver dependency
axum = {version = "0.7", optional=true}
hyper = { version = "1", features = ["http1", "server"], optional=true}
http = { version = "1", optional=true}
futures-util = {version = "0.3", optional=true}
http-body-util = {version = "0.1", optional=true}
inventory = "0.3.21"
serde.workspace = true
typetag.workspace = true
serde_json.workspace = true

[features]
default = ["http-receiver"]
receivers = ["dep:tokio","dep:tower", "dep:tokio-util"]
http-receiver = ["receivers", "dep:axum", "dep:hyper", "dep:http", "dep:futures-util", "dep:http-body-util"]
